name = "DLMReader"
uuid = "e1d33f9a-7203-49d2-8e1a-e3c4f85197b8"
authors = ["sl-solution <github.sl.solution@icloud.com> and contributors"]
version = "0.4.15"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InMemoryDatasets = "5c01b14b-ab03-46ff-b164-14c663efdd9f"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
InMemoryDatasets = "0.3, 0.4, 0.5, 0.6, 0.7"
InlineStrings = "1.0"
julia = "1.6"
Reexport = "0.1, 0.2, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
